version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: boxera-laravel
    container_name: boxera-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./laravel/:/var/www
    networks:
      - boxera

  db:
    image: mysql:8.0
    container_name: boxera-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - boxera

  nginx:
    image: nginx:alpine
    container_name: boxera-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./laravel/:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - boxera

networks:
  boxera:
    driver: bridge
